---
title: "miloR + slingshot .. continuous DA"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages

```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(miloR)
  library(SingleCellExperiment)
  library(dplyr)
  library(tibble)
  library(slingshot)
  library(scater)
  library(scran)
  library(bluster)
  library(reshape2)
  library(BiocParallel)
  library(distinct)
  library(cowplot)
})

```

## Read in data, quick peek at low dim projection

```{r}
sce <- readRDS("/data/day1_differential_analysis/sce_continuum_demo_public.rds")
plotUMAP(sce, colour_by="condition", shape_by="sample") +
  geom_point(size=3, aes(colour=colour_by, shape=shape_by))
```


## Run miloR analysis

```{r}
# general flow taken from:
# https://www.bioconductor.org/packages/release/bioc/vignettes/miloR/inst/doc/milo_demo.html

# create milo object
milo <- Milo(sce)
reducedDim(milo, "UMAP") <- reducedDim(sce, "UMAP")


# using parameters from vignette, build graph (see scran::buildKNNGraph for arguments)
milo <- buildGraph(milo, k=10, d=30)
# define neighborhoods and select median nodes/vertices 
milo <- makeNhoods(milo, k=10, d=30)
# check the number of cells belonging to a neighborhood
plotNhoodSizeHist(milo) 

# count by sample for each neighbourhood
milo <- countCells(milo,
                   meta.data=data.frame(colData(milo)),
                   sample="sample")
milo <- calcNhoodDistance(milo, d=30)

nhcnts <- nhoodCounts(milo)

# quick peek at neighbourhood counts
head(nhcnts[,sort(colnames(nhcnts))])


# collect metadata, make design matrix
md <- as.data.frame(colData(milo))
md <- unique(md[,c("sample","condition")])
rownames(md) <- md$sample

# check
all( colnames(nhcnts) == rownames(md) )

# doing tests for each neighbourhood
milo_res <- testNhoods(milo, design=~condition, design.df=md)

# peek at results
milo_res %>% arrange(SpatialFDR) %>% head(20)


# visualize neighbourhood-wise results in low dim projection
milo <- buildNhoodGraph(milo)
plotNhoodGraphDA(milo, milo_res)
```




## Differential abundance of pseudotimes across trajectories

### Run `slingshot` analysis

```{r}
sce$cluster <- clusterCells(sce, use.dimred="PCA", BLUSPARAM=NNGraphParam(k=3))

df <- data.frame(reducedDim(sce, "UMAP")[,1:2], cluster=sce$cluster)
df_agg <- df %>% group_by(cluster) %>% summarise_all(mean)


# quick look on the clustering
plotUMAP(sce, colour_by="cluster") +
  geom_label(data=df_agg, aes(x=X1, y=X2, label=cluster))
  

sling <- slingshot(sce, clusterLabels = 'cluster', reducedDim = 'PCA')

# quick look on the trajectory inference
curves <- slingCurves(sling, as.df=TRUE)
p1 <- plotReducedDim(sling, "PCA") + 
  geom_path(aes(x=PC1, y=PC2, group=Lineage, colour=factor(Lineage)),
            data=curves, lwd=1.5)

ps <- lapply(1:3, FUN=function(x){
  plotReducedDim(sling, "PCA", colour_by=paste0("slingPseudotime_",x)) +
    geom_path(data=curves[curves$Lineage==x,], aes(x=PC1,y=PC2), lwd=1.5)
})
plot_grid(plotlist=c(list(p1),ps))
```

### Visualize pseudotime relative abundances

```{r}
# transformations of inferred trajectory data
md <- slingPseudotime(sling) %>%
  as.data.frame() %>%
  mutate(cell_id = sling$cell_id,
         cluster = sling$cluster,
         condition = sling$condition,
         sample = sling$sample)
head(md, 3)

md_melt <- melt(md)
head(md_melt, 3)

# get cluster positions on the lineages
df_agg <- aggregate(md[,1:3], by=md[,"cluster",drop=FALSE], na.rm=TRUE, FUN=mean)

lin <- "Lineage2"
ggplot(md_melt %>% filter(variable==lin)) +
  geom_density(aes(x = value, fill = condition, group = sample), alpha = .5) +
  geom_label(data=df_agg, aes(Lineage2, y=0, label=cluster))
```

### Test for differences using distinct

```{r}
# build a pseudotime SE
sse <- SummarizedExperiment(list(pseudotime=t(slingPseudotime(sling))),
                            colData=colData(sling)[,c("sample","condition")])
sse$dummy <- 1L # `distinct` will need a cluster column

# build a (sample-level) model matrix
df <- unique(colData(sse))
row.names(df) <- df$sample
mm <- model.matrix(~condition, data=df)

# run distinct for each trajectory:
pvals <- bplapply(setNames(row.names(sse),row.names(sse)),
                BPPARAM=MulticoreParam(3), FUN=function(x){
  # we have to double the row to avoid an error in distinct
  sse2 <- sse[rep(x,2),!is.na(assay(sse)[x,])]
  distinct_test(sse2, name_assays_expression="pseudotime",
                name_cluster="dummy", name_sample="sample", design=mm)[1,3]
})
pvals
```

