---
title: "Cluster-based DA exercise"
author: "Pierre-Luc"
date: "4/19/2022"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment) # core sc infrastructures
  library(edgeR) # differential expression analysis
  library(ggplot2) # for plotting
  library(patchwork) # for combining plots
  library(ComplexHeatmap) # for plotting heatmaps
})
```

We build the abundances object:

```{r}
sce <- readRDS("/data/day1_differential_analysi/DA_example2.SCE.rds")
cluster_abundances <- reshape2::dcast(as.data.frame(colData(sce)), cluster_id~sample_id)
row.names(cluster_abundances) <- cluster_abundances$cluster_id
cla <- SummarizedExperiment(list(counts=as.matrix(cluster_abundances[,-1])))
cla$group <- factor(ifelse(grepl("LPS",colnames(cla)),"LPS","Control"))
assays(cla)$proportion <- 100*t(t(assay(cla))/colSums(assay(cla)))

Heatmap(t(scale(t(assays(cla)$proportion))), column_split=cla$group, name="scaled %")
```

Or visualizing it differently:

```{r}
# quick fn to compare the proportions across groups
plotProps <- function(cla, assay="proportion"){
  # get the mean proportions per group
  m <- sapply(split(seq_len(ncol(cla)), cla$group), FUN=function(i){
    rowMeans(assays(cla)[[assay]][,i])
  })
  m <- cbind(cluster_id=row.names(m), as.data.frame(m))
  ggplot(m, aes(Control, LPS, colour=cluster_id)) + geom_abline() + 
    geom_point(show.legend=FALSE) + 
    ggtitle(assay) + scale_x_log10() + scale_y_log10()
}
plotProps(cla)
```

## Exercise

Let's try the two methods we've seen in this example.

What are your expectations?
